### Health check
GET {{host}}/
Accept: application/json

### register user
POST {{host}}/register
Content-Type: application/json

{
  "username": "sojborg",
  "email": "hamselv",
  "password": "123"
}

### login user
POST {{host}}/login
Content-Type: application/json

{
  "email": "jesper@mail.com",
  "password": "hemmeligt"
}

### update user password
PUT {{host}}/user/61e693e6c026d8057db4d846
Content-Type: application/json
token: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTY5M2U2YzAyNmQ4MDU3ZGI0ZDg0NiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NDI1MTY3MjMsImV4cCI6MTY0Mjk0ODcyM30.tx-HJujq_RDg9SREBIPwUwDl8tsJxerpiLYkXD1TlaI

{
  "password": "hemmeligt1"
}

### chat message
POST {{host}}/message
Content-Type: application/json

{
  "message": "hej med dig"
}

### Get channel chats
GET {{host}}/channel/61e68a6a6642d355e0004a91
Content-Type: application/json

### create new channel
POST {{host}}/channel
Content-Type: application/json
token: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTY5M2U2YzAyNmQ4MDU3ZGI0ZDg0NiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NDI1MTY3MjMsImV4cCI6MTY0Mjk0ODcyM30.tx-HJujq_RDg9SREBIPwUwDl8tsJxerpiLYkXD1TlaI

{
  "name": "coding"
}

### Get all channels
GET {{host}}/channels
Content-Type: application/json
token: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZTY5M2U2YzAyNmQ4MDU3ZGI0ZDg0NiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NDI5NDg3NjUsImV4cCI6MTY0MzM4MDc2NX0.ilriWHQ_JScyig9zhgSL9G0njGkDyq1lIFG5hjEK0r4
